basePath: /
definitions:
  models.Comment:
    properties:
      created_at:
        type: string
      id:
        type: integer
      message:
        type: string
      photo:
        $ref: '#/definitions/models.Photo'
      photo_id:
        type: integer
      updated_at:
        type: string
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: integer
    type: object
  models.Photo:
    properties:
      User:
        $ref: '#/definitions/models.User'
      caption:
        type: string
      created_at:
        type: string
      id:
        type: integer
      photo_url:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  models.SocialMedia:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      social_media_url:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      age:
        type: integer
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      profile_image_url:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Documentation Final Project
  title: Final Project
  version: "1.0"
paths:
  /comments:
    get:
      description: get comments
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Comment'
            type: array
      security:
      - BearerAuth: []
      summary: Fetch comments
      tags:
      - Comment
    post:
      description: create and store an comment
      parameters:
      - description: Comments's Message
        in: formData
        name: message
        required: true
        type: string
      - description: Comments's Photo ID
        in: formData
        name: photo_id
        required: true
        type: integer
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Comment'
      security:
      - BearerAuth: []
      summary: Create an comment
      tags:
      - Comment
  /comments/{commentId}:
    delete:
      description: delete an comment by ID
      parameters:
      - description: Comment ID
        in: path
        name: commentId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete an comment
      tags:
      - Comment
    get:
      description: Retrieve a comment by its ID
      parameters:
      - description: Comment ID
        in: path
        name: commentId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Comment'
      security:
      - BearerAuth: []
      summary: Get a comment by ID
      tags:
      - Comment
    put:
      description: update an comment by ID
      parameters:
      - description: Comment ID
        in: path
        name: commentId
        required: true
        type: integer
      - description: Comments's Message
        in: formData
        name: message
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Photo'
      security:
      - BearerAuth: []
      summary: Update an comment
      tags:
      - Comment
  /photos:
    get:
      description: get photos
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Photo'
            type: array
      security:
      - BearerAuth: []
      summary: Fetch photos
      tags:
      - Photo
    post:
      description: create and store an photo
      parameters:
      - description: Photo's Title
        in: formData
        name: title
        required: true
        type: string
      - description: Photo's Caption
        in: formData
        name: caption
        required: true
        type: string
      - description: Photo's Photo URL
        in: formData
        name: photo_url
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Photo'
      security:
      - BearerAuth: []
      summary: Create an photo
      tags:
      - Photo
  /photos/{photoId}:
    delete:
      description: delete an photo by ID
      parameters:
      - description: Photo ID
        in: path
        name: photoId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete an photo
      tags:
      - Photo
    get:
      description: Retrieve a photo by its ID
      parameters:
      - description: Photo ID
        in: path
        name: photoId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Photo'
      security:
      - BearerAuth: []
      summary: Get a photo by ID
      tags:
      - Photo
    put:
      description: update an photo by ID
      parameters:
      - description: Photo ID
        in: path
        name: photoId
        required: true
        type: integer
      - description: Photo's Title
        in: formData
        name: title
        required: true
        type: string
      - description: Photo's Caption
        in: formData
        name: caption
        required: true
        type: string
      - description: Photo's Photo URL
        in: formData
        name: photo_url
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Photo'
      security:
      - BearerAuth: []
      summary: Update an photo
      tags:
      - Photo
  /socialmedias:
    get:
      description: get socialMedias
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SocialMedia'
            type: array
      security:
      - BearerAuth: []
      summary: Fetch socialMedias
      tags:
      - Social Media
    post:
      description: create and store an socialMedia
      parameters:
      - description: Social Media's Name
        in: formData
        name: name
        required: true
        type: string
      - description: Social Media's Social Media URL
        in: formData
        name: social_media_url
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.SocialMedia'
      security:
      - bearerAuth: []
      summary: Create an socialMedia
      tags:
      - Social Media
  /socialmedias/{socialMediaId}:
    delete:
      description: delete an socialMedia by ID
      parameters:
      - description: SocialMedia ID
        in: path
        name: socialMediaId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete an socialMedia
      tags:
      - Social Media
    get:
      description: Retrieve social media by its ID
      parameters:
      - description: Social Media ID
        in: path
        name: socialMediaId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SocialMedia'
      security:
      - BearerAuth: []
      summary: Get social media by ID
      tags:
      - Social Media
    put:
      description: update an socialMedia by ID
      parameters:
      - description: SocialMedia ID
        in: path
        name: socialMediaId
        required: true
        type: integer
      - description: Social Media's Name
        in: formData
        name: name
        required: true
        type: string
      - description: Social Media's Social Media URL
        in: formData
        name: social_media_url
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update an socialMedia
      tags:
      - Social Media
  /users:
    delete:
      consumes:
      - application/json
      description: delete an user by ID
      produces:
      - application/json
      responses:
        "200":
          description: Your comment has been successfully deleted
          schema:
            items:
              type: object
            type: array
      security:
      - BearerAuth: []
      summary: Delete an user
      tags:
      - User
    put:
      consumes:
      - application/json
      description: update an user by ID
      parameters:
      - description: User's Email
        in: formData
        name: email
        required: true
        type: string
      - description: User's Username
        in: formData
        name: username
        required: true
        type: string
      - description: User's Age
        in: formData
        name: age
        required: true
        type: integer
      - description: User's Password
        in: formData
        name: password
        required: true
        type: string
      - description: User's Profile Image URL
        in: formData
        name: profile_image_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update an user
      tags:
      - User
  /users/login:
    post:
      description: get an user by ID
      parameters:
      - description: User's Email
        in: formData
        name: email
        required: true
        type: string
      - description: User's Password
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Show an user
      tags:
      - User
  /users/register:
    post:
      description: create and store an user
      parameters:
      - description: User's Email
        in: formData
        name: email
        required: true
        type: string
      - description: User's Username
        in: formData
        name: username
        required: true
        type: string
      - description: User's Age
        in: formData
        name: age
        required: true
        type: integer
      - description: User's Password
        in: formData
        name: password
        required: true
        type: string
      - description: User's Profile Image URL
        in: formData
        name: profile_image_url
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
      summary: Create an user
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
